#!/usr/bin/env python3
"""Refresh checked-in deterministic example harnesses."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from eval_deterministic_profiles import EXAMPLE_GENERATED_DATE
from generate_minimal_harness import PROFILES, generate


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXAMPLE_ROOT = REPO_ROOT / "examples" / "deterministic"


def write_index(example_root: Path, generated_date: str) -> None:
    profiles = "\n".join(f"- `{profile}`" for profile in sorted(PROFILES))
    (example_root / "README.md").write_text(
        f"""# Deterministic Examples

These checked-in examples are generated by `scripts/refresh_deterministic_examples.py`.
They show the minimal Codex harness contract for each deterministic starter
profile. They are useful for inspection, docs, and eval coverage, but they are
not substitutes for richer live `/create` examples.

Generated date: `{generated_date}`

Profiles:

{profiles}

Refresh:

```bash
python scripts/refresh_deterministic_examples.py
python scripts/run_evals.py
```
""",
        encoding="utf-8",
    )


def refresh_examples(example_root: Path, generated_date: str) -> list[Path]:
    if example_root.exists():
        shutil.rmtree(example_root)
    example_root.mkdir(parents=True, exist_ok=True)
    write_index(example_root, generated_date)

    generated = []
    for profile in sorted(PROFILES):
        target = example_root / profile
        generate(target, None, profile, force=False, generated_date=generated_date)
        generated.append(target)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--example-root", default=DEFAULT_EXAMPLE_ROOT.as_posix(), help="Directory to refresh")
    parser.add_argument("--generated-date", default=EXAMPLE_GENERATED_DATE, help="Stable generated date for examples")
    args = parser.parse_args()

    generated = refresh_examples(Path(args.example_root).resolve(), args.generated_date)
    print(f"Refreshed {len(generated)} deterministic examples:")
    for path in generated:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
