#!/usr/bin/env python3
"""Refresh checked-in brief-based deterministic acceptance examples."""

from __future__ import annotations

import argparse
import shutil
from dataclasses import dataclass
from pathlib import Path

from run_brief_acceptance import run_brief_acceptance
from run_create_acceptance import DEFAULT_CREATED, DEFAULT_GENERATED_DATE


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXAMPLE_ROOT = REPO_ROOT / "examples" / "brief-acceptance"


@dataclass(frozen=True)
class BriefExample:
    slug: str
    project_name: str
    brief: str


BRIEF_EXAMPLES = (
    BriefExample(
        slug="rag-quality",
        project_name="RAG Quality Harness",
        brief="RAG app with prompts, evals, retrieval quality checks, and tool calls.",
    ),
    BriefExample(
        slug="security-review",
        project_name="Security Review Harness",
        brief="Security audit for CVE exposure, vulnerability triage, threat model, and remediation.",
    ),
    BriefExample(
        slug="support-escalation",
        project_name="Support Escalation Harness",
        brief="Customer support ticket escalation with FAQ grounding, privacy checks, and refund policy guardrails.",
    ),
    BriefExample(
        slug="hiring-scorecard",
        project_name="Hiring Scorecard Harness",
        brief="Hiring pipeline with candidate scorecards, interview rubric, and fairness review.",
    ),
)


def write_index(example_root: Path, generated_date: str, created: str, examples: tuple[BriefExample, ...]) -> None:
    example_list = "\n".join(f"- `{example.slug}`: {example.brief}" for example in examples)
    (example_root / "README.md").write_text(
        f"""# Brief Acceptance Examples

These checked-in examples are generated by `scripts/refresh_brief_acceptance_examples.py`.
They show the deterministic brief-based acceptance flow: brief recommendation,
profile selection, trigger preflight, generated harness, eval/smoke, and
`PROFILE_SELECTION.md`.

They are deterministic acceptance examples, not live model-mediated `/create`
transcripts.

Created timestamp: `{created}`
Generated date: `{generated_date}`

Examples:

{example_list}

Refresh:

```bash
python scripts/refresh_brief_acceptance_examples.py
python scripts/run_evals.py
```
""",
        encoding="utf-8",
    )


def refresh_examples(
    example_root: Path,
    examples: tuple[BriefExample, ...],
    generated_date: str,
    created: str,
) -> list[Path]:
    if example_root.exists():
        shutil.rmtree(example_root)
    example_root.mkdir(parents=True, exist_ok=True)
    write_index(example_root, generated_date, created, examples)

    generated = []
    for example in examples:
        target = example_root / example.slug
        try:
            target_label = target.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            target_label = target.name
        run_brief_acceptance(
            target=target,
            brief=example.brief,
            project_name=example.project_name,
            notes="checked-in deterministic brief acceptance example",
            force=False,
            generated_date=generated_date,
            created=created,
            limit=3,
            allow_low_confidence=False,
            target_label=target_label,
        )
        generated.append(target)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--example-root", default=DEFAULT_EXAMPLE_ROOT.as_posix(), help="Directory to refresh")
    parser.add_argument("--example", action="append", dest="examples", help="Example slug to refresh; repeat for more than one")
    parser.add_argument("--generated-date", default=DEFAULT_GENERATED_DATE, help="Stable generated date for examples")
    parser.add_argument("--created", default=DEFAULT_CREATED, help="Stable Created timestamp for examples")
    args = parser.parse_args()

    by_slug = {example.slug: example for example in BRIEF_EXAMPLES}
    examples = tuple(by_slug[slug] for slug in args.examples) if args.examples else BRIEF_EXAMPLES
    generated = refresh_examples(Path(args.example_root).resolve(), examples, args.generated_date, args.created)
    print(f"Refreshed {len(generated)} brief acceptance example(s):")
    for path in generated:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
