#!/usr/bin/env python3
"""Refresh checked-in deterministic preset /create acceptance examples."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

from generate_minimal_harness import PROFILES
from run_create_acceptance import DEFAULT_CREATED, DEFAULT_GENERATED_DATE, run_acceptance


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EXAMPLE_ROOT = REPO_ROOT / "examples" / "create-acceptance"
DEFAULT_PROFILES = tuple(sorted(PROFILES))


def write_index(example_root: Path, generated_date: str, created: str, profiles: tuple[str, ...]) -> None:
    profile_list = "\n".join(f"- `{profile}`" for profile in profiles)
    (example_root / "README.md").write_text(
        f"""# Create Acceptance Examples

These checked-in examples are generated by `scripts/refresh_create_acceptance_examples.py`.
They show the deterministic preset `/create` acceptance flow: trigger preflight,
`CREATION_CONTEXT.md`, preset harness generation, final eval/smoke, and
`CREATE_ACCEPTANCE_REPORT.md`.

They are still deterministic acceptance examples, not live model-mediated
`/create` transcripts.

Created timestamp: `{created}`
Generated date: `{generated_date}`

Profiles:

{profile_list}

Refresh:

```bash
python scripts/refresh_create_acceptance_examples.py
python scripts/run_evals.py
```
""",
        encoding="utf-8",
    )


def refresh_examples(example_root: Path, profiles: tuple[str, ...], generated_date: str, created: str) -> list[Path]:
    if example_root.exists():
        shutil.rmtree(example_root)
    example_root.mkdir(parents=True, exist_ok=True)
    write_index(example_root, generated_date, created, profiles)

    generated = []
    for profile in profiles:
        target = example_root / profile
        try:
            target_label = target.relative_to(REPO_ROOT).as_posix()
        except ValueError:
            target_label = target.name
        run_acceptance(
            target=target,
            profile=profile,
            project_name=None,
            project_type=profile.replace("-", " "),
            notes="checked-in deterministic create acceptance example",
            force=False,
            generated_date=generated_date,
            created=created,
            target_label=target_label,
        )
        generated.append(target)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--example-root", default=DEFAULT_EXAMPLE_ROOT.as_posix(), help="Directory to refresh")
    parser.add_argument("--profile", action="append", dest="profiles", help="Profile to refresh; repeat for more than one")
    parser.add_argument("--generated-date", default=DEFAULT_GENERATED_DATE, help="Stable generated date for examples")
    parser.add_argument("--created", default=DEFAULT_CREATED, help="Stable Created timestamp for examples")
    args = parser.parse_args()

    profiles = tuple(args.profiles) if args.profiles else DEFAULT_PROFILES
    generated = refresh_examples(Path(args.example_root).resolve(), profiles, args.generated_date, args.created)
    print(f"Refreshed {len(generated)} create acceptance example(s):")
    for path in generated:
        print(f"- {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
